### ISSUE TITLE
Failed to load the quick-jump package

### ISSUE THREAD

**Issue by prassie** [adrianlee44/atom-aligner#20]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.13.0

### Stack Trace

Failed to load the quick-jump package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/C:/Users/prasannar/.atom/packages/quick-jump/lib/quick-jump-view.coffee:4:199)
    at /C:/Users/prasannar/.atom/packages/quick-jump/lib/quick-jump-view.coffee:9:5
    at Object.<anonymous> (/C:/Users/prasannar/.atom/packages/quick-jump/lib/quick-jump-view.coffee:275:5)
    at Object.<anonymous> (/C:/Users/prasannar/.atom/packages/quick-jump/lib/quick-jump-view.coffee:277:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\prasannar\AppData\Local\atom\app-0.207.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "hex",
      "js-refactor",
      "local-server",
      "vertical-align",
      "vim-mode",
      "zentabs",
      "scope-inspector",
      "regex-railroad-diagram",
      "refactor",
      "project-colorize",
      "pomodoro",
      "neon-selection",
      "mobile-preview",
      "Zen",
      "block-travel",
      "git-difftool",
      "angularjs",
      "merge-conflicts",
      "language-objective-c",
      "archive-view",
      "background-tips",
      "dev-live-reload",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-mustache",
      "language-make",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "open-on-github",
      "package-generator",
      "welcome",
      "linter-gjslint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
column-select, v0.2.0
highlight-selected, v0.9.3
linter, v0.12.6
linter-csslint, v0.0.13
linter-jscs, v1.12.0
linter-jshint, v0.1.6
linter-jsonlint, v0.1.4
linter-less, v0.5.0
linter-scss-lint, v1.0.4
open-recent, v2.2.4
quick-jump, v0.0.4
word-jumper, v0.3.0

# Dev
No dev packages
```

**Comment by adrianlee44** [comment]
@prassie,
I don't see `aligner` as installed packages and I believe this error is thrown from [quick-jump](https://atom.io/packages/quick-jump).

**Comment by adrianlee44** [comment]
Closing this issue since there hasn't been activity for 28 days. Please reopen this issue if it's still a problem.
