### ISSUE TITLE
Uncaught TypeError: Cannot read property 'selector' of null

### ISSUE THREAD

**Issue by SeanJM** [adrianlee44/atom-aligner#28]
[Enter steps to reproduce below:]

1. in JavaScript, use aligner to align :

```javascript
  var target              = this.event.target;
  var inDropdown          = isNode(target.closest('.dropdown'));
  var isScrollbar         = helper.scrollbar.isComponent(target);
  var isInit              = dingo.keys(this.node).has('dingo_init');
  var scrollInDropdown = isScrollbar && inDropdown;
```

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.16.0

### Stack Trace

Uncaught TypeError: Cannot read property 'selector' of null

```
At /Users/sean/.atom/packages/aligner/lib/operator-config.coffee:131

TypeError: Cannot read property 'selector' of null
    at OperationConfig.getConfig (/Users/sean/.atom/packages/aligner/lib/operator-config.coffee:131:5)
    at Object.getTokenizedAlignCharacter (/Users/sean/.atom/packages/aligner/lib/helper.coffee:137:1)
    at Aligner.alignAtRow (/Users/sean/.atom/packages/aligner/lib/main.coffee:13:5)
    at Aligner.align (/Users/sean/.atom/packages/aligner/lib/main.coffee:13:5)
    at atom-text-editor.<anonymous> (/Users/sean/.atom/packages/aligner/lib/main.coffee:1:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)
```

### Commands

```
     -0:09.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:09.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:08.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:07.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:07.8.0 core:move-left (atom-text-editor.editor.is-focused)
  6x -0:07.7.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:06.4.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  5x -0:06.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:05.2.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:04.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:03.1.0 aligner:align (atom-text-editor.editor.is-focused)
     -0:02.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:02.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:00.4.0 aligner:align (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/sean/Dropbox/",
    "ignoredNames": [
      ".sass-cache",
      "node_modules",
      ".git",
      "bin",
      ".DS_Store*"
    ],
    "disabledPackages": [
      "css-comb",
      "csscomb"
    ],
    "themes": [
      "one-light-ui",
      "myth-syntax"
    ]
  },
  "aligner": {
    ":-leftSpace": true,
    ",-leftSpace": true,
    ":-alignment": "left"
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.16.0
aligner-css, v1.2.0
aligner-scss, v1.1.0
color-picker, v2.0.11
emmet, v2.3.12
myth-syntax, v0.0.0

# Dev
No dev packages
```

**Comment by adrianlee44** [comment]
@SeanJM, thanks for reporting this. Looking into this.

**Comment by SeanJM** [comment]
It's broken for JavaScript. You're welcome.

**Comment by adrianlee44** [comment]
Due to previous implementation of Aligner, updating aligner caused the package to get into a buggy state. `v0.16.1` should fix this problem here on out but for now, please restart Atom. Thanks!
