### ISSUE TITLE
Uncaught Error: Aligner: Package has already been activated

### ISSUE THREAD

**Issue by rugk** [adrianlee44/atom-aligner#29]
[Enter steps to reproduce below:]

0. Installing latest update
1. In my case I went to a php file
2. Ctrl+Shift+P and select align there.

**Atom Version**: 1.0.11
**System**: Windows 7
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.16.0

### Stack Trace

Uncaught Error: Aligner: Package has already been activated

```
At C:\Users\%username%\.atom\packages\aligner\lib\provider-manager.coffee:19

Error: Aligner: Package has already been activated
  at Error (native)
  at ProviderManager.register (C:\Users\%username%\.atom\packages\aligner\lib\provider-manager.coffee:13:13)
  at Aligner.registerProviders (C:\Users\%username%\.atom\packages\aligner\lib\main.coffee:1:1)
  at Provider.module.exports.Provider.provide (C:\Users\%username%\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
  at C:\Users\%username%\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -4:50.1.0 editor-stats:toggle (atom-workspace.workspace.scrollbars-visible-always)
     -3:27.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:28.7.0 core:backspace (input.hidden-input)
     -0:11.5.0 editor:copy-path (input.hidden-input)
     -0:10.5.0 command-palette:toggle (input.hidden-input)
     -0:08.6.0 core:confirm (input.hidden-input)
     -0:08.6.0 aligner:align (input.hidden-input)
```

### Config

```json
{
  "core": {
    "projectHome": "D:\\Users\\%username%\\GitHub",
    "disabledPackages": [
      "metrics",
      "autocomplete-emojis",
      "highlight-column",
      "tab-rename",
      "character-table",
      "placeholder-text"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.16.0
aligner-php, v1.0.0
[...]

# Dev
No dev packages
```

**Comment by rugk** [comment]
BTW this only happened directly after the installation of the latest update.

**Comment by adrianlee44** [comment]
@rugk, thanks for reporting this. Did this show up again after restarting Atom?

**Comment by rugk** [comment]
No.

**Comment by adrianlee44** [comment]
Due to previous implementation of Aligner, updating aligner caused the package to get into a buggy state. `v0.16.1` should fix this problem here on out but for now, please restart Atom. Thanks!

**Comment by kieranklaassen** [comment]
Yes, after restarting it is fixed. Thanks
