### ISSUE TITLE
Uncaught TypeError: path.extname is not a function

### ISSUE THREAD

**Issue by rugk** [adrianlee44/atom-aligner#31]
[Enter steps to reproduce below:]

1. Go to the settings of a package with keybindings.
2. At the keybindings, click on the 'copy' icon

**Atom Version**: 1.0.15
**System**: Windows 7
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.16.1

### Stack Trace

Uncaught TypeError: path.extname is not a function

```
At C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-keymap-view.js:147

TypeError: path.extname is not a function
  at PackageKeymapView.module.exports.PackageKeymapView.writeKeyBindingToClipboard (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-keymap-view.js:147:30)
  at HTMLSpanElement.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\settings-view\lib\package-keymap-view.js:139:24)
  at space-pen-section.jQuery.event.dispatch (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-section.elemData.handle (C:\Users\%username%\AppData\Local\atom\app-1.0.15\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -1:59.2.0 editor:duplicate-lines (atom-text-editor.editor.is-focused)
     -1:57.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:43.8.0 core:paste (atom-text-editor.editor.is-focused)
  3x -1:37.9.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -1:31.7.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:31.2.0 core:delete (atom-text-editor.editor.is-focused)
     -1:29.1.0 core:save (atom-text-editor.editor.is-focused)
  5x -1:26.4.0 tree-view:toggle (atom-text-editor.editor.is-focused)
  4x -1:21.9.0 pane:show-next-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:46.9.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:44.5.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:24.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:23.8.0 core:redo (atom-text-editor.editor.is-focused)
     -0:22.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:21.3.0 core:redo (div.settings-view.pane-item)
     -0:19.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "projectHome": "D:\\Users\\%username%\\GitHub",
    "disabledPackages": [
      "autocomplete-emojis",
      "metrics"
    ],
    "packagesWithKeymapsDisabled": []
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.16.1
aligner-php, v1.0.0
aligner-scss, v1.1.0
[...]

# Dev
No dev packages
```

**Comment by adrianlee44** [comment]
This is a bug on Atom's Settings View.

You can refer to atom/settings-view#652 for more information. The bug seems to be fixed with atom/settings-views#657.
