### ISSUE TITLE
Uncaught Error: Aligner: aligner-ruby has already been activated

### ISSUE THREAD

**Issue by fabien-michel** [adrianlee44/atom-aligner#36]
1. Update to last version

Fail when updating, but update seems success

**Atom Version**: 1.0.19
**System**: Mac OS X 10.9.5
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.17.0

### Stack Trace

Uncaught Error: Aligner: aligner-ruby has already been activated

```
At /Users/admin/.atom/packages/aligner/lib/provider-manager.coffee:5

Error: Aligner: aligner-ruby has already been activated
  at Error (native)
  at ProviderManager.register (/Users/admin/.atom/packages/aligner/lib/provider-manager.coffee:5:13)
  at Aligner.registerProviders (/Users/admin/.atom/packages/aligner/lib/main.coffee:49:77)
  at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```

### Commands

```
     -3:38.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -3:36.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:36.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:28.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -3:28 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:28 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:22.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -3:15.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:14.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:14.3.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -3:09.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -2:39.9.0 encoding-selector:show (atom-text-editor.editor)
     -0:20.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "rails-snippets",
      "editor-background",
      "linter-ruby"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.0
aligner-ruby, v1.4.0
aligner-scss, v1.1.0
atomatigit, v1.5.4
color-picker, v2.0.12
duplicate-line-or-selection, v0.5.0
highlight-selected, v0.10.1
language-asp, v1.0.0
language-diff, v0.3.1
minimap, v4.13.4
pigments, v0.15.0
project-manager, v2.6.1
rails-i18n, v0.1.3
recent-projects, v0.8.8
ruby-block, v0.3.5
ruby-slim, v0.2.0
tree-view-open-files, v0.2.4

# Dev
No dev packages
```

**Comment by adrianlee44** [comment]
Thanks for reporting the bug. Restarting Atom will fix this bug.

It was due to improper handling of activation and deactivation of aligner. This is patched in v0.17.0 and should be fixed from v0.17.0 onward.
