### ISSUE TITLE
Uncaught Error: Tried to create a gutter with a name that is already in use.

### ISSUE THREAD

**Issue by sztanpet** [adrianlee44/atom-aligner#37]
[Enter steps to reproduce below:]

1. open a file, have at least two panes open
2. drag one open file from one pane to the other

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.17.0

### Stack Trace

Uncaught Error: Tried to create a gutter with a name that is already in use.

```
At C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\src\gutter-container.js:36

Error: Tried to create a gutter with a name that is already in use.
  at GutterContainer.module.exports.GutterContainer.addGutter (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\src\gutter-container.js:36:15)
  at TextEditor.module.exports.TextEditor.addGutter (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\src\text-editor.js:2613:35)
  at EditorLinter.addGutter (f:\dropbox\atomsettings\packages\linter\lib\editor-linter.js:106:33)
  at EditorLinter.handleGutter (f:\dropbox\atomsettings\packages\linter\lib\editor-linter.js:99:14)
  at f:\dropbox\atomsettings\packages\linter\lib\editor-linter.js:50:13
  at Config.module.exports.Config.observeKeyPath (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\src\config.js:568:7)
  at Config.module.exports.Config.observe (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\src\config.js:135:21)
  at new EditorLinter (f:\dropbox\atomsettings\packages\linter\lib\editor-linter.js:48:40)
  at EditorRegistry.create (f:\dropbox\atomsettings\packages\linter\lib\editor-registry.coffee:13:24)
  at Linter.createEditorLinter (f:\dropbox\atomsettings\packages\linter\lib\linter.coffee:80:5)
  at f:\dropbox\atomsettings\packages\linter\lib\linter.coffee:36:71
  at C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\src\workspace.js:281:16
  at C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\src\workspace.js:342:18
  at Emitter.module.exports.Emitter.emit (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane-container.js:352:27)
  at C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane-container.js:339:26
  at Emitter.module.exports.Emitter.emit (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:345:20)
  at Pane.module.exports.Pane.moveItemToPane (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:439:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:706:20)
  at TabBarView.module.exports.TabBarView.onDrop (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:632:23)
  at space-pen-ul.<anonymous> (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\sztanpet\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -6:29.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -6:28 core:confirm (atom-text-editor.editor.mini.is-focused)
 17x -6:17.5.0 find-and-replace:find-next (atom-text-editor.editor.is-focused)
     -5:50 core:close (atom-text-editor.editor.is-focused)
     -5:46.1.0 core:save (atom-text-editor.editor.is-focused)
  3x -5:44.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:39.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:39 core:save (atom-text-editor.editor.is-focused)
  6x -3:54.1.0 find-and-replace:find-next (atom-text-editor.editor.is-focused)
     -3:36.4.0 core:close (atom-text-editor.editor.is-focused)
 12x -3:28.9.0 find-and-replace:find-next (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ],
    "projectHome": "F:\\Dropbox\\atomprojects",
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "line-ending-selector",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-objective-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "open-on-github"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.0
cursor-blink-interval, v0.3.1
go-plus, v3.5.1
go-runtime, v0.2.0
line-ending-selector-unix, v0.0.9
linter, v1.8.1
linter-php, v1.0.5
linter-phpmd, v1.2.1
project-manager, v2.6.1
Sublime-Style-Column-Selection, v1.3.0

# Dev
No dev packages
```

**Comment by adrianlee44** [comment]
Based on the stack trace, this error is caused by linter v1.8.1.
