### ISSUE TITLE
Failed to activate the aligner-php package

### ISSUE THREAD

**Issue by rugk** [adrianlee44/atom-aligner#42]
1. Deactivate and activate  aligner-php package

**Atom Version**: 1.2.4
**System**: Windows 7
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.17.2

### Stack Trace

Failed to activate the aligner-php package

```
At aligner-php has already been activated

Error: aligner-php has already been activated
    at Error (native)
    at OperationConfig.add (D:\Users\%username%\.atom\packages\aligner\lib\operator-config.coffee:33:13)
    at ProviderManager.register (D:\Users\%username%\.atom\packages\aligner\lib\provider-manager.coffee:10:37)
    at Aligner.registerProviders (D:\Users\%username%\.atom\packages\aligner\lib\main.coffee:66:38)
    at Provider.module.exports.Provider.provide (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
    at ServiceHub.module.exports.ServiceHub.provide (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\service-hub\lib\service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:330:71)
    at Package.module.exports.Package.activateNow (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:173:16)
    at C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:150:32
    at Package.module.exports.Package.measure (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:92:15)
    at C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:143:26
    at Package.module.exports.Package.activate (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package-manager.js:512:21)
    at C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package-manager.js:333:19
    at C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:588:20
    at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:773:29)
    at Config.module.exports.Config.setRawValue (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:565:19)
    at Config.module.exports.Config.set (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:226:14)
    at Config.module.exports.Config.removeAtKeyPath (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\config.js:343:12)
    at Package.module.exports.Package.enable (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\src\package-manager.js:162:14)
    at HTMLButtonElement.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\settings-view\lib\package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (C:\Users\%username%\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -2:39.3.0 editor-stats:toggle (atom-workspace.workspace.scrollbars-visible-always)
     -0:29.4.0 window:toggle-dev-tools (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-emojis",
      "metrics",
      "package-cop",
      "markdown-table-formatter",
      "tree-view-breadcrumb"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.2
aligner-php, v1.0.0
aligner-scss, v1.1.0
[...]

# Dev
No dev packages
```

**Comment by adrianlee44** [comment]
Are you updating from v0.17.1?

**Comment by rugk** [comment]
As it seems:
> **Thrown From:** aligner package, v0.17.2

Yes. :smile:

**Comment by rugk** [comment]
Yes I think so.
