### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, scandir 'D:\MSOCache'

### ISSUE THREAD

**Issue by rugk** [adrianlee44/atom-aligner#44]
[Enter steps to reproduce below:]

1. Just opened my whole drive (e.g. `D:\` on Windows) in Atom - it did not worked very nice.

But the real cause of this seem to be some directories, which Atom cannot access, because administrative rights are required (like `MSOCache` here).

**Atom Version**: 1.3.2
**System**: Windows 7, x64
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.17.4

### Stack Trace

Uncaught Error: EPERM: operation not permitted, scandir 'D:\MSOCache'

```
At fs.js:813

Error: EPERM: operation not permitted, scandir 'D:\MSOCache'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at Object.fsPlus.listSync (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\fs-plus\lib\fs-plus.js:171:18)
    at Directory.module.exports.Directory.squashDirectoryNames (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tree-view\lib\directory.js:379:23)
    at new Directory (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tree-view\lib\directory.js:28:25)
    at Directory.module.exports.Directory.getEntries (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tree-view\lib\directory.js:256:30)
    at Directory.module.exports.Directory.reload (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tree-view\lib\directory.js:312:20)
    at Directory.module.exports.Directory.expand (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tree-view\lib\directory.js:356:12)
    at tree-view-directory.DirectoryView.expand (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tree-view\lib\directory-view.js:177:24)
    at tree-view-directory.DirectoryView.initialize (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tree-view\lib\directory-view.js:81:21)
    at TreeView.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tree-view\lib\tree-view.js:571:16)
    at TreeView.module.exports.TreeView.updateRoots (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tree-view\lib\tree-view.js:576:10)
    at C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tree-view\lib\tree-view.js:361:24
    at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Project.module.exports.Project.addPath (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\src\project.js:255:29)
    at AtomEnvironment.module.exports.AtomEnvironment.openLocations (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\src\atom-environment.js:1028:26)
    at EventEmitter.outerCallback (C:\Users\%username%\AppData\Local\atom\app-1.3.2\resources\app.asar\src\application-delegate.js:201:18)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:12 editor-stats:toggle (atom-workspace.workspace.scrollbars-visible-always)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-emojis",
      "metrics",
      "tree-view-background",
      "markdown-table-formatter",
      "atom-beautify",
      "linter-js-standard",
      "linter-flake8",
      "tree-view-breadcrumb",
      "autocomplete-php",
      "linter-pep8",
      "copy-paste"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "regex-railroad-diagram"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.17.4
aligner-php, v1.0.0
aligner-python, v1.0.1
aligner-scss, v1.1.0
[...]

# Dev
No dev packages
```

**Comment by adrianlee44** [comment]
Aligner doesn't use `fs-plus` package. It seems like the error message is coming from `tree-view` package which is Atom core package showing the directory tree. I would suggest filing this issue under that repo.
