### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by rugk** [adrianlee44/atom-aligner#48]
[Enter steps to reproduce below:]

1. Open a tab in a second pane. (in my case the markdown preview)
2. Close it.

**Atom Version**: 1.4.1
**System**: Windows 7 x64
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.18.1

### Stack Trace

Uncaught TypeError: Cannot read property 'forEach' of undefined

```
At C:\Users\%username%\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:24

TypeError: Cannot read property 'forEach' of undefined
    at module.exports.CompositeDisposable.dispose (C:\Users\%username%\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:24:25)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\%username%\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.destroyed (C:\Users\%username%\AppData\Local\atom\app-1.4.1\resources\app.asar\src\pane.js:648:20)
    at Pane.module.exports.Model.destroy (C:\Users\%username%\AppData\Local\atom\app-1.4.1\resources\app.asar\src\model.js:31:58)
    at Pane.module.exports.Pane.destroy (C:\Users\%username%\AppData\Local\atom\app-1.4.1\resources\app.asar\src\pane.js:639:39)
    at Pane.module.exports.Pane.removeItem (C:\Users\%username%\AppData\Local\atom\app-1.4.1\resources\app.asar\src\pane.js:411:21)
    at Pane.module.exports.Pane.destroyItem (C:\Users\%username%\AppData\Local\atom\app-1.4.1\resources\app.asar\src\pane.js:453:16)
    at atom-tabs.TabBarView.onClick (C:\Users\%username%\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:695:17)
```

### Commands

```
     -0:57 editor-stats:toggle (atom-workspace.workspace.scrollbars-visible-always)
     -0:14.3.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:12.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:12.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.3.0 markdown-preview:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-emojis",
      "metrics",
      "tree-view-background",
      "markdown-table-formatter",
      "atom-beautify",
      "linter-js-standard",
      "linter-flake8",
      "tree-view-breadcrumb",
      "copy-paste",
      "linter-jsonlint",
      "line-diff-details",
      "atom-autocomplete-php",
      "php-class-tree",
      "markdown-preview-opener"
    ],
    "packagesWithKeymapsDisabled": [
      "regex-railroad-diagram"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.18.1
aligner-php, v1.0.0
aligner-python, v1.0.1
aligner-scss, v1.1.0
atom-html-preview, v0.1.13
autoclose-html, v0.20.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-python, v1.5.1
autocomplete-xml, v0.8.1
autohide-tree-view, v0.25.1
color-picker, v2.1.1
docblock-format-helper, v0.3.0
docs-snippets, v0.8.0
editor-stats, v0.17.0
emmet, v2.4.1
figlet, v0.5.3
file-icons, v1.6.14
foldername-tabs, v0.1.8
highlight-column, v0.5.0
highlight-selected, v0.11.1
keyboard-localization, v1.4.14
language-apache, v1.4.0
language-autoit, v0.2.1
language-batch, v0.3.3
language-ini, v1.14.0
language-nginx, v0.6.1
language-pascal, v0.17.0
language-patch, v0.1.0
line-count-status, v0.0.3
linter, v1.11.3
linter-alex, v1.7.0
linter-eslint, v6.0.0
linter-htmlhint, v1.0.2
linter-pep8, v1.2.1
linter-php, v1.1.7
linter-phpmd, v1.4.1
linter-pylama, v0.2.6
linter-tidy, v2.1.0
markdown-scroll-sync, v2.0.3
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-codeglance, v0.4.5
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
minimap-split-diff, v0.3.0
opened-files, v0.2.8
package-cop, v0.2.10
php-cs-fixer, v2.5.2
php-debug, v0.2.1
pigments, v0.22.1
pretty-json, v0.4.1
python-isort, v0.0.7
python-tools, v0.6.7
python-yapf, v0.9.1
regex-railroad-diagram, v0.11.0
switcheroo, v1.1.0
tablr, v0.10.0
tabs-to-spaces, v1.0.1
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by adrianlee44** [comment]
Based on the stack trace, this error is coming from [tabs](https://github.com/atom/tabs). I would suggest filing this issue on that repo.

**Comment by rugk** [comment]
Thanks. I found it: https://github.com/atom/tabs/issues/253
It's now fixed with the latest version of another package.
