### ISSUE TITLE
Failed to load  the aligner package

### ISSUE THREAD

**Issue by kevinastone** [adrianlee44/atom-aligner#49]
On Atom startup, I'm getting:

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.3
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package, v0.19.0

### Stack Trace

Failed to load the aligner package

```
At /Users/kstone/.atom/packages/aligner/lib/formatter.js:28
    range.getRows().forEach((currentRow) => {
                                       ^
missing ) after argument list

/Users/kstone/.atom/packages/aligner/lib/formatter.js:28
    range.getRows().forEach((currentRow) => {
                                       ^
SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:411:25)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/kstone/.atom/packages/aligner/lib/main.coffee:4:19)
    at Object.<anonymous> (/Users/kstone/.atom/packages/aligner/lib/main.coffee:1:1)
    at Module._compile (module.js:428:26)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/kstone/Documents",
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "tree-view",
      "deprecation-cop",
      "fuzzy-finder",
      "metrics",
      "styleguide",
      "timecop",
      "fb-analytics-client",
      "emmet",
      "background-tips",
      "nuclide-language-hack"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.19.0
aligner-php, v1.0.0
aligner-python, v1.0.1
auto-detect-indentation, v0.4.2
auto-update-packages, v1.0.0
autocomplete-python, v1.6.1
docblockr, v0.7.3
editorconfig, v1.2.4
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.15.4
language-ini, v1.14.0
language-restructuredtext, v0.12.0
language-thrift, v1.0.2
minimap, v4.19.0
minimap-highlight-selected, v4.3.1
nuclide, v0.116.22040344
pigments, v0.24.1
project-manager, v2.7.5
seti-syntax, v0.4.1
seti-ui, v0.8.1
ssh-config, v0.10.1
tab-control, v0.6.9
tool-bar, v0.2.0
word-jumper, v0.3.0

# Dev
No dev packages
```

**Comment by adrianlee44** [comment]
Any chance you can update to Atom 1.5 and see if you are still seeing this issue?
