### ISSUE TITLE
Uncaught TypeError: Cannot read property 'reset' of null

### ISSUE THREAD

**Issue by Chifilly** [adrianlee44/atom-aligner#78]
[Enter steps to reproduce:]

1. Load a .js file
2. Try and align some code

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package 1.2.4

### Stack Trace

Uncaught TypeError: Cannot read property 'reset' of null

```
At C:\Users\Adam\AppData\Local\atom\app-1.25.0\resources\app\src\tokenized-line.js:20

TypeError: Cannot read property 'reset' of null
    at TokenizedLine.module.exports.TokenizedLine.getTokenIterator (~/AppData/Local/atom/app-1.25.0/resources/app/src/tokenized-line.js:20:38)
    at TokenizedLine.get (~/AppData/Local/atom/app-1.25.0/resources/app/src/tokenized-line.js:26:31)
    at Object.getAlignCharacter (/packages/aligner/lib/helper.js:50:32)
    at Aligner.alignAtRow (/packages/aligner/lib/main.js:40:30)
    at editor.getSelectedBufferRanges.forEach (/packages/aligner/lib/main.js:28:14)
    at Array.forEach (native)
    at Aligner.align (/packages/aligner/lib/main.js:25:38)
    at HTMLElement.disposables.add.atom.commands.add (/packages/aligner/lib/main.js:74:12)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.25.0/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.25.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.25.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -5:26.4.0 intentions:highlight (input.hidden-input)
  2x -5:26.3.0 atom-alignment:alignMultiple (input.hidden-input)
     -5:23.5.0 intentions:highlight (input.hidden-input)
     -5:23.5.0 core:select-all (input.hidden-input)
     -5:22.8.0 atom-alignment:alignMultiple (input.hidden-input)
     -5:22.1.0 intentions:highlight (input.hidden-input)
     -5:22 core:undo (input.hidden-input)
     -5:20.7.0 intentions:highlight (input.hidden-input)
     -5:20.5.0 core:save (input.hidden-input)
     -5:09.4.0 intentions:highlight (input.hidden-input)
     -5:09.2.0 aligner:align (input.hidden-input)
     -4:25.2.0 intentions:highlight (input.hidden-input)
     -4:24.9.0 color-picker:open (input.hidden-input)
     -0:04.7.0 intentions:highlight (input.hidden-input)
     -0:04.6.0 aligner:align (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-python 1.1.0 
aligner-scss 1.3.1 
atom-alignment 0.13.0 
atom-beautify 0.32.2 
atom-material-syntax 1.0.8 
atom-typescript 12.3.8 
autoclose-html 0.23.0 
autocomplete-paths 2.12.2 
autocomplete-python 1.10.5 
autoupdate-packages 1.3.1 
busy-signal 1.4.3 
color-picker 2.2.5 
css-declaration-sorter 1.2.0 
file-icons 2.1.18 
flex-tool-bar 2.0.0 
git-blame 1.6.0 
git-log 0.4.1 
git-time-machine 1.5.9 
goto-definition 1.3.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-docker 1.1.8 
language-ejs 0.4.0 
linter 2.2.0 
linter-docker 0.3.0 
linter-jshint 3.1.6 
linter-sass-lint 1.8.3 
linter-tslint 1.9.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-selection 4.5.0 
pigments 0.40.2 
pretty-json 2.0.0 
pristine-ui 1.1.11 
sync-settings 0.8.5 
todo-show 2.2.0 
toggler 0.3.1 
tool-bar 1.1.7 
tree-view-git-status 1.4.0 
unity-shader-files 0.3.1 
xml-formatter 0.11.0 
```

**Comment by Chifilly** [comment]
After some more testing, it seems it's only a problem when the "Use Tree Sitter Parsers" is enabled

**Comment by tithonium** [comment]
Error happens for me in ruby files.

**Comment by jmurowaniecki** [comment]
1. Open a bash file;
2. I selected some points (CTRL + D);
3. I navigated to the point where I would like to align;
4. Press CTRL + ALT + /;
5. :boom: 

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Ubuntu 18.04.1
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package 1.2.4


### Stack Trace

Uncaught TypeError: Cannot read property 'reset' of null

```
At /usr/share/atom/resources/app/static/<embedded>:14

TypeError: Cannot read property 'reset' of null
    at TokenizedLine.t.exports.TokenizedLine.getTokenIterator (/usr/share/atom/resources/app/static/<embedded>:14:107078)
    at TokenizedLine.get (/usr/share/atom/resources/app/static/<embedded>:14:107181)
    at Object.getAlignCharacter (/packages/aligner/lib/helper.js:50:33)
    at Aligner.alignAtRow (/packages/aligner/lib/main.js:40:30)
    at editor.getSelectedBufferRanges.forEach (/packages/aligner/lib/main.js:28:14)
    at Array.forEach (<anonymous>)
    at Aligner.align (/packages/aligner/lib/main.js:25:38)
    at HTMLElement.disposables.add.atom.commands.add (/packages/aligner/lib/main.js:74:12)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:349858)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1230399)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1226533)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:285037)
```

### Commands

```
     -1:00.9.0 editor:move-to-first-character-of-line (input.hidden-input)
     -1:00.6.0 intentions:highlight (input.hidden-input)
     -1:00.5.0 editor:select-to-end-of-word (input.hidden-input)
     -1:00.2.0 find-and-replace:select-next (input.hidden-input)
  2x -0:59.8.0 core:move-right (input.hidden-input)
     -0:59.5.0 intentions:highlight (input.hidden-input)
     -0:59.4.0 editor:move-to-end-of-word (input.hidden-input)
     -0:53.7.0 core:move-down (input.hidden-input)
     -0:53.3.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:53 intentions:highlight (input.hidden-input)
     -0:52.9.0 editor:select-to-end-of-word (input.hidden-input)
     -0:52.7.0 find-and-replace:select-next (input.hidden-input)
     -0:52.4.0 editor:move-to-end-of-word (input.hidden-input)
     -0:51.7.0 core:move-right (input.hidden-input)
     -0:51.4.0 intentions:highlight (input.hidden-input)
     -0:49.6.0 aligner:align (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
busy-signal 1.4.3 
intentions 1.1.5 
jslint 1.5.1 
language-docker 1.1.8 
linter 2.0.0 
linter-docker 0.3.2 
linter-php 1.5.1 
linter-ui-default 1.7.1 
markdown-scroll-sync 2.1.2 
monokai-seti 0.9.0 
seti-syntax 1.2.0 
seti-ui 1.11.0 
textmate-multimarkdown-syntax 0.1.0 
```

**Comment by skypress-bmo** [comment]
1. Navigate to a JS file, and a group of lines to align
2. Use Ctl + Alt + /

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: linux 4.18.16-96.current
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package 1.2.4


### Stack Trace

Uncaught TypeError: Cannot read property 'reset' of null

```
At /usr/share/atom/resources/app/static/<embedded>:14

TypeError: Cannot read property 'reset' of null
    at TokenizedLine.t.exports.TokenizedLine.getTokenIterator (/usr/share/atom/resources/app/static/<embedded>:14:107041)
    at TokenizedLine.get (/usr/share/atom/resources/app/static/<embedded>:14:107144)
    at Object.getAlignCharacter (/packages/aligner/lib/helper.js:50:33)
    at Aligner.alignAtRow (/packages/aligner/lib/main.js:40:30)
    at editor.getSelectedBufferRanges.forEach (/packages/aligner/lib/main.js:28:14)
    at Array.forEach (<anonymous>)
    at Aligner.align (/packages/aligner/lib/main.js:25:38)
    at HTMLElement.disposables.add.atom.commands.add (/packages/aligner/lib/main.js:74:12)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:345848)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1226096)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1222230)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:281284)
```

### Commands

```
  5x -9:16.2.0 core:backspace (input.hidden-input)
     -0:53 intentions:highlight (input.hidden-input)
     -0:52.8.0 aligner:align (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-javascript 1.3.0 
aligner-php 1.3.0 
atom-beautify 0.33.4 
atom-minify 0.8.0 
atom-typescript 12.7.3 
busy-signal 1.4.3 
docblockr 0.13.7 
intentions 1.1.5 
language-docker 1.1.8 
linter 2.2.0 
linter-docker 0.3.2 
linter-js-yaml 1.3.0 
linter-php 1.5.1 
linter-sass-lint 1.8.3 
linter-ui-default 1.7.1 
minimap 4.29.9 
ninja-atom-syntax 0.1.2 
pretty-json 2.0.3 
```

**Comment by cldwalker** [comment]
I ran into this bug on atom 1.38.2 for a simple js alignment case. When I upgraded to 1.40.0-beta1
 via Atom Beta, I no longer saw this bug. Seems https://github.com/atom/atom/pull/19538 addressed the issue 🎉

**Comment by adrianlee44** [comment]
It has been at least 5 minor version since 1.40.0 and hopefully everyone has upgraded. I'm going to close this issue now.
