### ISSUE TITLE
Failed to activate the aligner package

### ISSUE THREAD

**Issue by selectedxp** [adrianlee44/atom-aligner#84]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Linux Lite
**Thrown From**: [aligner](https://github.com/adrianlee44/atom-aligner) package 1.2.4

### Stack Trace

Failed to activate the aligner package

```
At Cannot find module 'extend'

Error: Cannot find module 'extend'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/aligner/lib/operator-config.js:7:16)
    at /packages/aligner/lib/operator-config.js:202:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/aligner/lib/main.js:7:24)
    at /packages/aligner/lib/main.js:91:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:688157)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3304913)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3292897)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:3292675)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3290285)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:3292535)
    at new Promise (<anonymous>)
```

### Commands

```
```

### Non-Core Packages

```
aligner 1.2.4 
aligner-css 1.2.1 
aligner-javascript 1.3.0 
aligner-php 1.3.0 
aligner-python 1.2.0 
aligner-typescript 1.0.0 
aligner 1.2.4 
atom-beautify 0.33.4 
atom-debug-ui 1.0.4 
atom-ide-ui 0.13.0 
ide-php 0.7.18 
php-debug 0.3.5 
```

**Comment by adrianlee44** [comment]
I'm not sure if you have resolved this issue but based on the error message, it seems like one of the dependencies were not installed correctly.

I'm going to close this for now.
